const KEY='better-mvp-v1';
const seed={onboard:false,demo:false,profile:{name:'Nela',goal:'Become stronger, healthier and more confident.',priorities:['Health','Achievement','Freedom'],time:'30 min',budget:'',structure:'Balanced',interests:['Fitness','Beauty']},goals:[{id:1,title:'Build a stronger, healthier routine',description:'Train consistently while keeping the plan realistic.',priority:5,progress:42}],tasks:[{id:1,title:"Complete today's workout",time:35,reason:'Fitness is one of your highest priorities.',status:'open'},{id:2,title:'Review tomorrow’s top priority',time:5,reason:'A small planning action keeps the week clear.',status:'open'},{id:3,title:'Take one recovery action',time:10,reason:'Consistency includes recovery.',status:'open'}],skipReasons:[],beauty:{skin:'Not set',hair:'Not set',aesthetic:'Natural / polished',budget:'Not set'},fitness:{workouts:12,volume:1840,last:'Upper body'},factors:[['Performance',30],['Price',25],['Quality',20],['Appearance',15],['Convenience',10]],decisionOptions:[{name:'Option A',performance:9,price:6,quality:8,appearance:7,convenience:7},{name:'Option B',performance:7,price:9,quality:8,appearance:8,convenience:9}]};
let s=JSON.parse(localStorage.getItem(KEY)||JSON.stringify(seed));let view=s.onboard?'home':'landing';let step=0;let temp={};
let cloudTimer=null;
function save(){localStorage.setItem(KEY,JSON.stringify(s)); if(!s.demo){clearTimeout(cloudTimer); cloudTimer=setTimeout(()=>saveCloudState(s).catch(e=>console.warn('BETTER cloud save failed',e)),350)}}
async function bootstrapAccount(){try{const session=await getSession(); if(!session)return; const cloud=await loadCloudState(); if(cloud&&typeof cloud==='object'){s={...seed,...cloud,profile:{...seed.profile,...(cloud.profile||{})}}; s.demo=false; localStorage.setItem(KEY,JSON.stringify(s)); render()} else {await saveCloudState(s); await saveCloudProfile(s.profile.name||'')}}catch(e){console.warn('BETTER account sync unavailable',e)}}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function nav(v){view=v;render()}function demo(){s=JSON.parse(JSON.stringify(seed));s.onboard=true;s.demo=true;s.profile.name='Alex';localStorage.setItem(KEY,JSON.stringify(s));view='home';render()}function start(){step=0;temp={};view='onboard';render()}
function shell(content){const items=[['home','Home'],['goals','Goals'],['daily','Daily Plan'],['decisions','Decisions'],['beauty','Beauty'],['fitness','Fitness'],['profile','Profile']];return `<header class="nav"><div class="navin"><button class="logo" onclick="nav('home')">BETTER</button>${s.demo?'<span class="demo">DEMO PROFILE</span>':''}<span id="accountStatus" class="authbar"></span><nav class="links">${items.map(x=>`<button class="${view===x[0]?'active':''}" onclick="nav('${x[0]}')">${x[1]}</button>`).join('')}</nav><button class="secondary" onclick="demo()">Try Demo</button></div></header><main class="main">${content}</main><footer class="footer"><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a><a href="/feedback.html">Feedback</a><span class="muted">BETTER public beta · no live research in this MVP</span></footer><nav class="mobile">${[['home','Home'],['goals','Goals'],['daily','Plan'],['decisions','Decide'],['profile','Profile']].map(x=>`<button class="${view===x[0]?'active':''}" onclick="nav('${x[0]}')">${x[1]}</button>`).join('')}</nav>`}
function landing(){return `<section class="hero"><div><span class="eyebrow">Personal improvement system</span><h1>Become Better. Intentionally.</h1><p>BETTER learns what you're trying to become, helps you make smarter decisions, and turns your goals into actions you can actually follow.</p><div class="actions"><button class="primary" onclick="start()">Start My Plan</button><button class="secondary" onclick="demo()">Try Demo</button></div></div></section><section class="grid">${[['Understand yourself','BETTER builds a personal model around your goals, preferences, constraints and priorities.'],['Make decisions for YOU','Compare options according to what actually matters to you instead of generic rankings.'],['Know what to do next','Turn long-term goals into realistic daily actions.'],['Adapt to real life','Miss something? BETTER adjusts instead of punishing you.'],['Your personal improvement system','Future expansion: Beauty, Fitness, Gaming, Career, Shopping and Learning.'],['Built for trust','Research and evidence will show sources, dates, confidence and uncertainty when connected.']].map(x=>`<div class="card"><h3>${x[0]}</h3><p class="muted">${x[1]}</p></div>`).join('')}</section>`}
const ons=[['Direction','What are you trying to improve?',()=>`<div class="choices">${['Appearance','Fitness','Career','Money','Skills','Gaming','Confidence','Organization','Other'].map(x=>`<button class="choice ${(temp.interests||[]).includes(x)?'selected':''}" onclick="pickInterest('${x}')">${x}</button>`).join('')}</div>`],['Future','What does your ideal future look like?',()=>`<textarea id="goal" placeholder="Describe the life you're working toward...">${esc(temp.goal||'')}</textarea>`],['Priorities','What matters most?',()=>`<div class="choices">${['Money','Time','Health','Appearance','Freedom','Security','Fun','Learning','Achievement','Relationships'].map(x=>`<button class="choice ${(temp.priorities||[]).includes(x)?'selected':''}" onclick="togglePriority('${x}')">${x}</button>`).join('')}</div>`],['Friction','What usually gets in your way?',()=>`<div class="choices">${['Lack of time','Lack of money','Motivation','Confusion','Too many choices','Forgetting','Complicated websites','Not knowing what to do','Other'].map(x=>`<button class="choice ${temp.friction===x?'selected':''}" onclick="temp.friction='${x}';render()">${x}</button>`).join('')}</div>`],['Structure','How much structure do you want?',()=>`<div class="choices">${['Gentle','Balanced','Strict'].map(x=>`<button class="choice ${temp.structure===x?'selected':''}" onclick="temp.structure='${x}';render()">${x}</button>`).join('')}</div>`],['Capacity','How much time can you realistically spend each day?',()=>`<div class="choices">${['15 min','30 min','60 min','90+ min'].map(x=>`<button class="choice ${temp.time===x?'selected':''}" onclick="temp.time='${x}';render()">${x}</button>`).join('')}</div>`],['Budget',"What's your approximate discretionary monthly budget?",()=>`<input id="budget" value="${esc(temp.budget||'')}" placeholder="Amount, or Prefer not to say"><p class="muted">You can change this later.</p>`]];
function pickInterest(x){temp.interests=[x];render()}function togglePriority(x){temp.priorities=temp.priorities||[];temp.priorities=temp.priorities.includes(x)?temp.priorities.filter(a=>a!==x):[...temp.priorities,x];render()}function onboard(){const o=ons[step];return `<section class="onboard"><div class="progress">${ons.map((_,i)=>`<i class="${i<=step?'on':''}"></i>`).join('')}</div><span class="eyebrow">0${step+1} / ${o[0]}</span><h1>${o[1]}</h1>${o[2]()}<div class="actions"><button class="secondary" ${step?'':'disabled'} onclick="step--;render()">Back</button><button class="primary" onclick="nextOnboard()">${step===6?'Create My Plan':'Continue'}</button></div></section>`}
function nextOnboard(){if(step===1)temp.goal=document.getElementById('goal').value;if(step===6)temp.budget=document.getElementById('budget').value;if(step===6){s.onboard=true;s.profile={...s.profile,...temp};save();view='home'}else step++;render()}
function home(){return `<div class="title"><div><span class="eyebrow">${s.demo?'Demo profile · ':''}Today</span><h1>Good morning, ${esc(s.profile.name)}</h1></div></div><div class="card"><span class="eyebrow">Your direction</span><h2>${esc(s.profile.goal)}</h2><p class="muted">Strict about the goal. Flexible about the route.</p></div><div class="title" style="margin-top:28px"><h2>Today's priorities</h2><span class="pill">${s.tasks.filter(t=>t.status==='done').length}/${s.tasks.length} complete</span></div><div class="stack">${s.tasks.map(taskCard).join('')}</div>`}
function taskCard(t){return `<div class="card task"><div class="taskinfo"><span class="pill">${t.time} min</span><h3>${esc(t.title)}</h3><p class="muted">${esc(t.reason)}</p>${t.status!=='open'?`<span class="pill">${t.status}</span>`:''}</div><div class="actions"><button class="primary" ${t.status==='done'?'disabled':''} onclick="done(${t.id})">DONE</button><button class="secondary" ${t.status!=='open'?'disabled':''} onclick="skip(${t.id})">SKIP</button><button class="secondary" onclick="adjust(${t.id})">ADJUST</button></div></div>`}
function done(id){s.tasks=s.tasks.map(t=>t.id===id?{...t,status:'done'}:t);save();render()}
function skip(id){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="skipModal" role="dialog" aria-modal="true"><div class="modal-card"><span class="eyebrow">No shame. Learn from it.</span><h2>Why didn't this happen?</h2><p class="muted">Your answer helps BETTER make future plans more realistic.</p><div class="choices">${['Too busy','Too difficult','Forgot','Didn’t feel like it','Not important anymore','Something unexpected happened','Other'].map(r=>`<button class="choice" onclick="confirmSkip(${id},${JSON.stringify(r)})">${r}</button>`).join('')}</div><button class="secondary" onclick="closeSkip()">Cancel</button></div></div>`)}
function confirmSkip(id,reason){s.tasks=s.tasks.map(t=>t.id===id?{...t,status:'skipped'}:t);s.skipReasons.push({reason,date:new Date().toISOString()});save();closeSkip();render()}
function closeSkip(){document.getElementById('skipModal')?.remove()}
function adjust(id){s.tasks=s.tasks.map(t=>t.id===id?{...t,time:Math.max(5,Math.round(t.time*.7)),reason:'Adjusted to make the next step more realistic.',status:'open'}:t);save();render()}
function goals(){return `<div class="title"><div><span class="eyebrow">Direction → milestones → actions → habits</span><h1>Goals</h1></div></div><div class="card"><div class="field"><label>New goal</label><input id="newgoal" placeholder="What are you working toward?"><button class="primary" onclick="addGoal()">Create goal</button></div></div><div class="stack" style="margin-top:14px">${s.goals.map(g=>`<div class="card"><div class="title"><div><h3>${esc(g.title)}</h3><p class="muted">${esc(g.description)}</p></div><button class="danger" onclick="delGoal(${g.id})">Delete</button></div><div class="bar"><i style="width:${g.progress}%"></i></div><p class="muted">${g.progress}% progress · Priority ${g.priority}/5</p></div>`).join('')}</div>`}function addGoal(){const x=document.getElementById('newgoal').value.trim();if(x){s.goals.push({id:Date.now(),title:x,description:'New goal — add detail in your profile.',priority:3,progress:0});save();render()}}function delGoal(id){s.goals=s.goals.filter(g=>g.id!==id);save();render()}
function decisions(){const factors=s.factors;const scores=s.decisionOptions.map(o=>factors.reduce((a,f)=>a+(o[f[0].toLowerCase()]||0)*f[1],0)/100);const best=scores[0]>=scores[1]?0:1;return `<div class="title"><div><span class="eyebrow">Help Me Decide</span><h1>Choose for you</h1></div></div><div class="notice">Personalized match scores reflect your stated priorities. They are not objective universal ratings. Research mode is not connected in this demo.</div><div class="card" style="margin-top:14px"><h2>Best choice for you: ${s.decisionOptions[best].name}</h2><div class="score">${(scores[best]).toFixed(1)}/10</div><p class="muted">Personalized match score</p><p>Strengths: strong fit against your weighted priorities. Weaknesses: every choice gives something up. Tradeoff: the recommendation changes when factor importance changes.</p><p class="muted">What could change it? Adjust factor importance or add real evidence when research is connected.</p></div><div class="grid" style="margin-top:14px">${factors.map((f,i)=>`<div class="card"><b>${f[0]}</b><p class="muted">${f[1]}% importance</p><input type="range" min="0" max="50" value="${f[1]}" oninput="factor(${i},this.value)"></div>`).join('')}</div><div class="grid" style="margin-top:14px">${s.decisionOptions.map((o,i)=>`<div class="card"><h3>${o.name}</h3><div class="score">${scores[i].toFixed(1)}/10</div><p class="muted">Performance ${o.performance} · Price ${o.price} · Quality ${o.quality}</p></div>`).join('')}</div>`}function factor(i,v){s.factors[i][1]=+v;save();render()}
function beauty(){return `<div class="title"><div><span class="eyebrow">Personalized aesthetic system</span><h1>Beauty</h1></div></div><div class="grid"><div class="card"><h3>Beauty Profile</h3><p>Skin: ${s.beauty.skin}</p><p>Hair: ${s.beauty.hair}</p><p>Aesthetic: ${s.beauty.aesthetic}</p><p>Budget: ${s.beauty.budget}</p></div><div class="card"><h3>Hair</h3><p class="muted">Hairstyle ideas, color ideas, maintenance level and stylist instructions. Live local service data can be connected later.</p></div><div class="card"><h3>Makeup</h3><p class="muted">Everyday · Natural · Dramatic · Experimental. Recommendations explain the fit to your profile.</p></div><div class="card"><h3>Products</h3><p class="muted">Demo content only. Live prices, availability, reviews and retailers are not connected.</p></div></div>`}
function fitness(){return `<div class="title"><div><span class="eyebrow">Work alongside your existing program</span><h1>Fitness</h1></div></div><div class="grid"><div class="card"><h3>Progress</h3><div class="score">${s.fitness.workouts}</div><p class="muted">workouts logged</p><p>Volume: ${s.fitness.volume} units</p><p>Last: ${s.fitness.last}</p></div><div class="card"><h3>Log workout</h3><div class="field"><label>Exercise</label><input id="exercise" placeholder="e.g. Romanian deadlift"><label>Sets × reps × weight</label><input id="sets" placeholder="3 × 10 × 20 lb"><button class="primary" onclick="logWorkout()">Save workout</button></div></div><div class="card"><h3>Video analysis</h3><input type="file" accept="video/*"><p class="muted">Video analysis coming soon. No AI form analysis is performed in this MVP.</p></div></div>`}function logWorkout(){s.fitness.workouts++;s.fitness.last=document.getElementById('exercise').value||'New workout';save();render()}
function profile(){return `<div class="title"><div><span class="eyebrow">Your personal model</span><h1>My Profile</h1></div></div><div class="card"><div class="field"><label>Name</label><input id="pname" value="${esc(s.profile.name)}"><label>Primary direction</label><textarea id="pgoal">${esc(s.profile.goal)}</textarea><label>Available time</label><input id="ptime" value="${esc(s.profile.time)}"><label>Budget</label><input id="pbudget" value="${esc(s.profile.budget)}"><label>Structure</label><input id="pstructure" value="${esc(s.profile.structure)}"><button class="primary" onclick="saveProfile()">Save profile</button></div><div class="actions"><button class="secondary" onclick="exportBetterData()">Export my data</button><button class="secondary" onclick="importBetterData()">Import data</button><button class="danger" onclick="erase()">Delete local data</button></div></div><div class="account-note" style="margin-top:14px"><strong>Cloud sync</strong><p class="muted">${s.demo?'Demo profile is local-only.':'When you are signed in, BETTER syncs your profile and progress to your account so you can continue on another device.'}</p></div><div class="grid" style="margin-top:14px"><div class="card"><h3>Priorities</h3><p class="muted">${s.profile.priorities.join(' · ')||'Not set'}</p></div><div class="card"><h3>Interests</h3><p class="muted">${s.profile.interests.join(' · ')||'Not set'}</p></div><div class="card"><h3>Trust & evidence</h3><p class="muted">No live research is connected. BETTER will not fabricate sources, studies, prices or reviews.</p></div></div>`}function saveProfile(){s.profile.name=document.getElementById('pname').value;s.profile.goal=document.getElementById('pgoal').value;s.profile.time=document.getElementById('ptime').value;s.profile.budget=document.getElementById('pbudget').value;s.profile.structure=document.getElementById('pstructure').value;save();getSession().then(x=>x&&saveCloudProfile(s.profile.name).catch(e=>console.warn(e)));render()}function erase(){if(confirm('Delete all BETTER personal data from this browser?')){localStorage.removeItem(KEY);location.reload()}}
function account(){return `<section class="auth-card"><div class="card"><span class="eyebrow">Your BETTER account</span><h1>${authMode==='signup'?'Create an account':'Welcome back'}</h1><p class="muted">Your account syncs your BETTER progress across devices. Authentication is handled by Supabase; BETTER never stores your password.</p><label>Email</label><input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>Password</label><input id="authPassword" type="password" autocomplete="${authMode==='signup'?'new-password':'current-password'}" placeholder="At least 6 characters"><div id="authError" class="auth-error"></div><div class="actions"><button class="primary" onclick="submitAuth()">${authMode==='signup'?'Create account':'Log in'}</button><button class="secondary" onclick="toggleAuth()">${authMode==='signup'?'Already have an account':'Create a free account'}</button></div><button class="link-button" onclick="forgotPassword()">Forgot your password?</button><p class="muted" style="margin-top:14px">Free beta · no payment required.</p></div></section>`}
let authMode='signup';
function toggleAuth(){authMode=authMode==='signup'?'login':'signup';render()}
async function submitAuth(){const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value;if(!email||password.length<6){document.getElementById('authError').textContent='Enter a valid email and a password of at least 6 characters.';return}try{const r=authMode==='signup'?await signUp(email,password,s.profile.name||''):await signIn(email,password);if(r.error)throw r.error; if(authMode==='signup'&&r.data?.session===null){alert('Account created. Check your email to verify your address, then log in.')}else{await bootstrapAccount();alert('Signed in. Your BETTER data is synced.')}view='home';render()}catch(e){document.getElementById('authError').textContent=e.message||'Unable to authenticate.'}}
async function forgotPassword(){const email=document.getElementById('authEmail').value.trim();if(!email)return alert('Enter your email first.');try{const r=await resetPassword(email);if(r.error)throw r.error;alert('Password reset email sent. Check your inbox.')}catch(e){document.getElementById('authError').textContent=e.message||'Unable to send the reset email.'}}
async function handleResetPassword(){if(location.hash==='#reset-password'){const password=prompt('Choose a new password (at least 6 characters).');if(password&&password.length>=6){const r=await updatePassword(password);if(r.error)alert(r.error.message);else{history.replaceState(null,'',location.pathname);alert('Password updated.')}}}}
async function deleteMyAccount(){if(!confirm('Delete your BETTER account and all cloud-synced BETTER data? This cannot be undone.'))return;try{await deleteAccount();localStorage.removeItem(KEY);alert('Your account and cloud data were deleted.');location.reload()}catch(e){alert(e.message||'We could not delete the account.')}}
async function updateAccountBar(){const el=document.getElementById('accountStatus');if(!el)return;try{const session=await getSession();if(session)el.innerHTML=`<span class="account-pill">${esc(session.user.email)}</span><button class="secondary" onclick="logoutAccount()">Log out</button><button class="secondary" onclick="deleteMyAccount()">Delete account</button>`;else el.innerHTML=`<button class="secondary" onclick="nav('account')">Log in</button>`}catch{el.innerHTML=`<button class="secondary" onclick="nav('account')">Account</button>`}}
async function logoutAccount(){await signOut();render()}
function render(){let c=view==='landing'?landing():view==='onboard'?onboard():view==='account'?account():view==='home'||view==='daily'?home():view==='goals'?goals():view==='decisions'?decisions():view==='beauty'?beauty():view==='fitness'?fitness():profile();document.getElementById('app').innerHTML=shell(c);updateAccountBar()}render();
bootstrapAccount();
handleResetPassword();

// Public-beta enhancements: install prompt, feedback/privacy links, local export/import and graceful runtime error capture.
(function(){
  window.addEventListener('error', function(e){ console.error('BETTER runtime error', e.error || e.message); });
  window.addEventListener('unhandledrejection', function(e){ console.error('BETTER unhandled rejection', e.reason); });
  let deferredPrompt;
  window.addEventListener('beforeinstallprompt', function(e){ e.preventDefault(); deferredPrompt=e; showInstall(); });
  function showInstall(){
    if(document.querySelector('.install') || window.matchMedia('(display-mode: standalone)').matches) return;
    const el=document.createElement('div'); el.className='card install';
    el.innerHTML='<strong>Install BETTER</strong><p class="muted">Add BETTER to your home screen for a more app-like experience.</p><div class="actions"><button class="primary" id="installBetter">Install</button><button class="secondary" id="dismissInstall">Not now</button></div>';
    document.body.appendChild(el);
    document.getElementById('installBetter').onclick=async()=>{if(deferredPrompt){await deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;}el.remove()};
    document.getElementById('dismissInstall').onclick=()=>el.remove();
  }
  const oldShell=window.shell;
})();

// Data portability helpers exposed from Profile.
function exportBetterData(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='better-profile-export.json';a.click();URL.revokeObjectURL(a.href)}
function importBetterData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||typeof x!=='object')throw Error('Invalid file');s={...s,...x};save();render();alert('BETTER data imported.')}catch(e){alert('That file is not a valid BETTER export.')}};r.readAsText(f)};input.click()}
